version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  terraform-check:
    executor: terraform/default
    steps:
      - checkout

      - terraform/init:
          path: terraform

      - terraform/validate:
          path: terraform

      - terraform/plan:
          path: terraform

workflows:
  terraform-validate-and-plan:
    jobs:
      - terraform-check
          filters:
            branches:
              only:
                - master

